#define ENERGEST_CONF_ON 1

#define ENERGEST_CONF_ADDITIONS ENERGEST_TYPE_CUSTOM_LISTEN

#define SIMPLE_ENERGEST_CONF_PERIOD (CLOCK_SECOND * 5)

#define INT_CONF_TELEMETRY_EXPERIMENT_SIZE 8

#define TSCH_CONF_WITH_INT 0
