#define ENERGEST_CONF_ON 1

#define TELEMETRY_SIZE 19

#define ENERGEST_CONF_ADDITIONS ENERGEST_TYPE_CUSTOM_LISTEN

#define SIMPLE_ENERGEST_CONF_PERIOD (CLOCK_SECOND * 5)

#define INT_CONF_TELEMETRY_EXPERIMENT 1
#define INT_CONF_TELEMETRY_EXPERIMENT_SIZE TELEMETRY_SIZE

#define TSCH_CONF_WITH_INT 1

#define INT_CONF_PROBABILISTIC 0

#define TELEMETRY_CONF_COUNTER 1
