#ifndef _INT_CONF_H_
#define _INT_CONF_H_

#include "contiki.h"

#ifdef INT_CONF_MAX_TELEMETRY_ENTRIES
#define INT_MAX_TELEMETRY_ENTRIES
#else
#define INT_MAX_TELEMETRY_ENTRIES 16
#endif

#ifdef INT_MAX_CONTENT_ENTRIES
#define INT_MAX_CONTENT_ENTRIES
#else
#define INT_MAX_CONTENT_ENTRIES 1
#endif

#ifdef INT_CONF_TELEMETRY_EXPERIMENT
#define INT_TELEMETRY_EXPERIMENT INT_CONF_TELEMETRY_EXPERIMENT
#else
#define INT_TELEMETRY_EXPERIMENT 0
#endif

#ifdef INT_CONF_TELEMETRY_EXPERIMENT_SIZE
#define INT_TELEMETRY_EXPERIMENT_SIZE INT_CONF_TELEMETRY_EXPERIMENT_SIZE
#else
#define INT_TELEMETRY_EXPERIMENT_SIZE 5
#endif

#ifdef INT_CONF_PROBABILISTIC
#define INT_PROBABILISTIC INT_CONF_PROBABILISTIC
#else
#define INT_PROBABILISTIC 0
#endif

#define INT_SUBIE_ID 0xCA

#ifdef TELEMETRY_CONF_COUNTER
#define  INT_TELEMETRY_COUNTER  TELEMETRY_CONF_COUNTER
#else
#define INT_TELEMETRY_COUNTER 0
#endif 

#ifdef INT_ACTIVE_MONITORING_CONF
#define INT_ACTIVE_MONITORING INT_ACTIVE_MONITORING_CONF
#else
#define INT_ACTIVE_MONITORING 0
#endif

#endif