#define ENERGEST_CONF_ON 1

#define ENERGEST_CONF_ADDITIONS ENERGEST_TYPE_CUSTOM_LISTEN

#define SIMPLE_ENERGEST_CONF_PERIOD (CLOCK_SECOND * 5)

#define TSCH_CONF_WITH_INT 0

#define COAP_CONF_WITH_PIGGYBACKING 1
#define COAP_CONF_TELEMETRY_SIZE 4

#define LOG_CONF_LEVEL_COAP LOG_LEVEL_WARN
#define LOG_LEVEL_APP LOG_LEVEL_WARN